host: 0.0.0.0
port: 8080
keymap:
  - command: move_up
    events:
      - up
  - command: move_down
    events:
      - down
  - command: move_left
    events:
      - left
  - command: move_right
    events:
      - right
