keymap:
  - { keys: [alt+i], command: move_up, args: { count: 1 } }
  - { keys: [shift+alt+i], command: move_up, args: { count: 5 } }
  - { keys: [alt+k], command: move_down, args: { count: 1 } }
  - { keys: [shift+alt+k], command: move_down, args: { count: 5 } }
  - { keys: [alt+j], command: move_left }
  - { keys: [alt+l], command: move_right }
  - { keys: [ctrl+q], command: quit, contexts: [buffer, search] }
  - { keys: [ctrl+w], command: search }
  - { keys: [ctrl+e], command: save }
  - { keys: [esc], command: close, contexts: [search] }
  - { keys: [enter], command: submit, contexts: [search] }
