color_scheme:
  title:
    fg: "#c0c5ce"
    bg: "#1a1d23"  # HSL(224, 14, 12)
  tabs:
    dots:
      fg: "#c0c5ce"
      bg: "#1a1d23"  # HSL(224, 14, 12)
    active:
      fg: "#c0c5ce"
      bg: "#2b303b"
    primary:
      fg: "#c0c5ce"
      bg: "#1f2128"  # HSL(224, 14, 14)
    secondary:
      fg: "#c0c5ce"
      bg: "#1a1d23"  # HSL(224, 14, 12)
  buffer:
    selected:
      fg: "#c0c5ce"
      bg: "#2b303b"
    unselected:
      fg: "#c0c5ce"
      bg: "#2b303b"
keymap:
  - { keys: [alt+i], command: move_up, args: { count: 1 } }
  - { keys: [shift+alt+i], command: move_up, args: { count: 5 } }
  - { keys: [alt+k], command: move_down, args: { count: 1 } }
  - { keys: [shift+alt+k], command: move_down, args: { count: 5 } }
  - { keys: [alt+j], command: move_left }
  - { keys: [alt+l], command: move_right }
  - { keys: [shift+alt+j], command: previous_view }
  - { keys: [shift+alt+l], command: next_view }
  - { keys: [ctrl+q], command: quit, contexts: [buffer, search] }
  - { keys: [ctrl+w], command: search }
  - { keys: [ctrl+e], command: save }
  - { keys: [esc], command: close, contexts: [search] }
  - { keys: [enter], command: submit, contexts: [search] }
